import type { Metadata } from 'next'
import Link from "next/link";
import { Footer } from '@/components/layout/Footer'

export const metadata: Metadata = {
    title: 'Terms of Service | RentVault',
    description: 'Terms of Service for RentVault. Understand your rights, responsibilities, pricing, refunds, and limitation of liability.',
    alternates: {
        canonical: 'https://rentvault.ai/terms'
    }
}

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-white">
            <main className="max-w-[720px] mx-auto px-4 md:px-6 py-12 md:py-20">
                <h1 className="text-3xl md:text-4xl font-bold mb-8">Terms of Service</h1>

                <div className="prose prose-slate max-w-none">
                    <p className="text-lg text-slate-600 mb-8">
                        Last updated: December 2025
                    </p>

                    <section className="mb-10">
                        <h2 className="text-xl font-bold mb-4">1. About RentVault</h2>
                        <p className="text-slate-600">
                            RentVault is a documentation and organisation tool for tenants. It helps you store and organise rental documents, photos, and key dates in one secure place and generate reports for your personal records.
                        </p>
                    </section>

                    <section className="mb-10">
                        <h2 className="text-xl font-bold mb-4">2. Not legal advice</h2>
                        <p className="text-slate-600 font-semibold mb-4">
                            RentVault does not provide legal advice.
                        </p>
                        <p className="text-slate-600">
                            Any summaries, reminders, translations, or documents generated by RentVault are provided for convenience and organisational purposes only. You are responsible for reviewing your contract and deciding what actions to take. If you need legal advice, you should consult a qualified professional in your jurisdiction.
                        </p>
                    </section>

                    <section className="mb-10">
                        <h2 className="text-xl font-bold mb-4">3. Your responsibilities</h2>
                        <p className="text-slate-600 mb-4">
                            By using RentVault, you agree that:
                        </p>
                        <ul className="list-disc pl-6 space-y-2 text-slate-600">
                            <li>You are responsible for the accuracy of information you provide.</li>
                            <li>You will upload only content you have the right to use and share.</li>
                            <li>You will not upload unlawful content or use the service for unlawful purposes.</li>
                            <li>You will not attempt to interfere with, disrupt, or reverse engineer the service.</li>
                        </ul>
                    </section>

                    <section className="mb-10">
                        <h2 className="text-xl font-bold mb-4">4. Accounts and access</h2>
                        <p className="text-slate-600">
                            You are responsible for maintaining the security of your account and access to your email address. If you believe your account has been compromised, contact us promptly.
                        </p>
                    </section>

                    <section className="mb-10">
                        <h2 className="text-xl font-bold mb-4">5. Paid features, pricing, and payments</h2>
                        <p className="text-slate-600 mb-4">
                            RentVault offers optional paid features (such as official PDF exports and extended retention). Prices are displayed before purchase.
                        </p>
                        <p className="text-slate-600 mb-4">
                            Payments are processed by Stripe. Purchases are one-time unless explicitly stated otherwise.
                        </p>
                        <p className="text-slate-600">
                            Taxes (such as VAT) may apply depending on your location and will be shown at checkout where applicable.
                        </p>
                    </section>

                    <section className="mb-10">
                        <h2 className="text-xl font-bold mb-4">6. Refunds</h2>
                        <p className="text-slate-600 mb-4">
                            Because RentVault provides digital services and immediate access to features, refunds are not guaranteed.
                        </p>
                        <p className="text-slate-600 mb-4">
                            If you believe you were charged in error or experienced a technical issue that prevented you from using a paid feature, please contact us and we will review the request.
                        </p>
                        <p className="text-slate-600">
                            Contact: <a href="mailto:contact@rentvault.ai" className="text-slate-900 underline hover:no-underline">contact@rentvault.ai</a>
                        </p>
                    </section>

                    <section className="mb-10">
                        <h2 className="text-xl font-bold mb-4">7. Service availability and changes</h2>
                        <p className="text-slate-600 mb-4">
                            We aim to provide a reliable service but cannot guarantee uninterrupted availability.
                        </p>
                        <p className="text-slate-600">
                            We may update, modify, or discontinue parts of the service. Where changes materially affect paid features, we will make reasonable efforts to provide notice.
                        </p>
                    </section>

                    <section className="mb-10">
                        <h2 className="text-xl font-bold mb-4">8. Content and outputs</h2>
                        <p className="text-slate-600 mb-4">
                            You retain rights to the content you upload.
                        </p>
                        <p className="text-slate-600">
                            RentVault may generate outputs such as summaries, translations, reminders, and PDFs based on your inputs. These outputs are provided for convenience only and do not guarantee any outcome.
                        </p>
                    </section>

                    <section className="mb-10">
                        <h2 className="text-xl font-bold mb-4">9. Limitation of liability</h2>
                        <p className="text-slate-600 mb-4">
                            To the maximum extent permitted by law, RentVault is not liable for indirect, incidental, or consequential losses arising from your use of the service, including missed deadlines, deposit disputes, or reliance on generated summaries.
                        </p>
                        <p className="text-slate-600">
                            Nothing in these Terms limits liability where it cannot be limited under applicable law.
                        </p>
                    </section>

                    <section className="mb-10">
                        <h2 className="text-xl font-bold mb-4">10. Contact</h2>
                        <p className="text-slate-600 mb-4">
                            For questions about these Terms, contact us at:
                        </p>
                        <p className="text-slate-600 mb-4">
                            <a href="mailto:contact@rentvault.ai" className="text-slate-900 underline hover:no-underline">contact@rentvault.ai</a>
                        </p>
                        <p className="text-slate-600 mb-2">
                            For privacy-related requests:
                        </p>
                        <p className="text-slate-600">
                            <a href="mailto:contact@rentvault.ai" className="text-slate-900 underline hover:no-underline">contact@rentvault.ai</a>
                        </p>
                    </section>
                </div>
            </main>

            {/* Footer */}
            <Footer />
        </div>
    );
}
